import type { Commune } from "../types";

export const TEST_YEARS = [2020, 2021, 2022, 2023];

// A: Full data across all years, all fields populated including rent.
// Prices: 2000→2200→2400→2600 for easy % verification (+30% over full range)
const communeA: Commune = {
  city_code: "01001",
  city_name: "Ville-A",
  dept_code: "01",
  lat: 46.0,
  lon: 5.0,
  median_sqm: 2300,
  median_sqm_house: 1800,
  median_sqm_apt: 2800,
  median_sqm_land: 100,
  count: 200,
  count_house: 80,
  count_apt: 100,
  count_land: 20,
  rent_residential: 12,
  rent_house: 10,
  rent_apt: 14,
  rent_count_residential: 50,
  rent_count_house: 20,
  rent_count_apt: 30,
  years: {
    "2020": {
      median_sqm: 2000,
      median_sqm_house: 1600,
      median_sqm_apt: 2400,
      median_sqm_land: 80,
      count: 50,
      count_house: 20,
      count_apt: 25,
      count_land: 5,
      rent_residential: 10,
      rent_house: 8,
      rent_apt: 12,
      rent_count_residential: 12,
      rent_count_house: 5,
      rent_count_apt: 7,
    },
    "2021": {
      median_sqm: 2200,
      median_sqm_house: 1700,
      median_sqm_apt: 2600,
      median_sqm_land: 85,
      count: 55,
      count_house: 22,
      count_apt: 28,
      count_land: 5,
      rent_residential: 11,
      rent_house: 9,
      rent_apt: 13,
      rent_count_residential: 14,
      rent_count_house: 6,
      rent_count_apt: 8,
    },
    "2022": {
      median_sqm: 2400,
      median_sqm_house: 1900,
      median_sqm_apt: 2800,
      median_sqm_land: 90,
      count: 48,
      count_house: 18,
      count_apt: 24,
      count_land: 6,
      rent_residential: 12,
      rent_house: 10,
      rent_apt: 14,
      rent_count_residential: 16,
      rent_count_house: 7,
      rent_count_apt: 9,
    },
    "2023": {
      median_sqm: 2600,
      median_sqm_house: 2000,
      median_sqm_apt: 3000,
      median_sqm_land: 95,
      count: 52,
      count_house: 20,
      count_apt: 26,
      count_land: 6,
      rent_residential: 13,
      rent_house: 11,
      rent_apt: 15,
      rent_count_residential: 18,
      rent_count_house: 8,
      rent_count_apt: 10,
    },
  },
};

// B: Has apt data + rent, null land. Tests null-field handling and yield computation
const communeB: Commune = {
  city_code: "75056",
  city_name: "Paris",
  dept_code: "75",
  lat: 48.86,
  lon: 2.35,
  median_sqm: 10000,
  median_sqm_house: null,
  median_sqm_apt: 10500,
  median_sqm_land: null,
  count: 5000,
  count_house: 0,
  count_apt: 4800,
  count_land: null,
  rent_residential: 25,
  rent_house: undefined,
  rent_apt: 26,
  rent_count_residential: 200,
  rent_count_house: undefined,
  rent_count_apt: 190,
  years: {
    "2020": {
      median_sqm: 9500,
      median_sqm_apt: 10000,
      count: 1200,
      count_apt: 1100,
      rent_residential: 23,
      rent_apt: 24,
      rent_count_residential: 50,
      rent_count_apt: 45,
    },
    "2023": {
      median_sqm: 10500,
      median_sqm_apt: 11000,
      count: 1300,
      count_apt: 1200,
      rent_residential: 27,
      rent_apt: 28,
      rent_count_residential: 55,
      rent_count_apt: 50,
    },
  },
};

// C: One year only, low counts (< MIN_SAMPLES_PER_YEAR=15). Tests insufficient-data path
const communeC: Commune = {
  city_code: "99999",
  city_name: "Petit-Village",
  dept_code: "99",
  lat: 43.0,
  lon: 1.0,
  median_sqm: 1500,
  count: 10,
  count_house: 5,
  count_apt: 3,
  count_land: 2,
  years: {
    "2022": {
      median_sqm: 1500,
      median_sqm_house: 1200,
      count: 10,
      count_house: 5,
      count_apt: 3,
      count_land: 2,
    },
  },
};

// D: Aggregate only, empty years. Tests getStats returning null for specific years
const communeD: Commune = {
  city_code: "13055",
  city_name: "Marseille",
  dept_code: "13",
  lat: 43.3,
  lon: 5.37,
  median_sqm: 3000,
  median_sqm_house: 2500,
  median_sqm_apt: 3500,
  median_sqm_land: 150,
  count: 300,
  count_house: 100,
  count_apt: 180,
  count_land: 20,
  rent_residential: 14,
  rent_house: 11,
  rent_apt: 16,
  rent_count_residential: 60,
  rent_count_house: 25,
  rent_count_apt: 35,
  years: {},
};

export const TEST_COMMUNES: Commune[] = [communeA, communeB, communeC, communeD];
